<?php 
/** 
 * @var $block \Divido\DividoFinancing\Block\Head
 */
?>
<script> 
    __widgetConfig = {apiKey: '<?php echo $block->getDividoKey(); ?>'}
    const dividoEnv = '<?php echo $block->getPlatformEnv(); ?>';
    const dividoBranding = <?php echo $block->getBrandingJson(); ?>;
</script>
<script type="text/javascript" src="<?php echo $block->getScriptUrl(); ?>"></script>
<script>// <![CDATA[
    let dividoEnv = '<?= $block->getPlatformEnv(); ?>';
    function waitForElementToDisplay(selector, time) {
        if(document.querySelector(selector)!=null) {
            <?= (empty($block->getCalcConfApiUrl())) ? '__widgetInstance' : '__calculator'; ?>.init();
            return;
        }
        else {
            setTimeout(function() {
                waitForElementToDisplay(selector, time);
            }, time);
        }
    }
    
    require([
        'jquery',
        'domReady!'
    ], function ($) {
        waitForElementToDisplay('#dividoWidget', 1000); 
    });
// ]]>
</script>