<?php 
/** 
 * @var $block \Divido\DividoFinancing\Block\Head
 */

$calcJsDom = (empty($block->getCalcConfApiUrl())) ? '__widgetInstance' : '__calculator';
?>
<script> 
    __widgetConfig = {apiKey: '<?php echo $block->getShortApiKey(); ?>'}
    const dividoEnv = '<?php echo $block->getPlatformEnv(); ?>';
    const dividoBranding = <?php echo $block->getBrandingJson(); ?>;
</script>
<script type="text/javascript" src="<?php echo $block->getScriptUrl(); ?>"></script>
<script>// <![CDATA[
    function waitForElementToDisplay(selector, time) {
        if(document.querySelector(selector)!=null) {
            <?= $calcJsDom ?>.init();
            return;
        }
        else {
            setTimeout(function() {
                waitForElementToDisplay(selector, time);
            }, time);
        }
    }
    
    require([
        'jquery',
        'domReady!'
    ], function ($) {
        waitForElementToDisplay('#dividoWidget', 1000); 
    });
    <?php if(!empty($block->getCalcConfApiUrl())){ ?>
    window.__calculatorConfig = {
        calculatorApiPubUrl: '<?= $block->getCalcConfApiUrl(); ?>',
        apiKey: '<?= $block->getShortApiKey(); ?>',
        overrides: {
            theme: {
                modes: {
                    Lightbox: {
                        linkText: '<?= $block->getCalcLinkText(); ?>'
                    }
                }
            }
        }
    };
    <?php } ?>
// ]]>
</script>