<?php /* @var $block \Divido\DividoFinancing\Block\Product\View\Extra */?>
<?php if($block->loadWidget() && $block->showWidget()){ ?>
  <div id='dividoWidget'
    data-calculator-widget
    data-plans="<?php echo $block->getProductPlans(); ?>"
    data-amount="<?php echo $block->getProductAmount(); ?>"
    data-footnote="<?php echo $block->getFootnote(); ?>"
    data-button-text="<?php echo $block->getButtonText(); ?>"
    data-mode="<?php echo $block->getMode(); ?>"
    <?php echo $block->getLanguageOverride(); ?>
  ></div>
<script>
require(['jquery'], function(jQuery){
  var options = jQuery(".product-options-wrapper input, .product-options-wrapper select");
  for(var iteration = 0; iteration < options.length; iteration++){
    var option = options[iteration];
    option.addEventListener('change', function(){
      setTimeout(updatePrice,50);
    })
  }
  var updatePrice = function(){
    let threshold = <?php echo $block->getThreshold(); ?>;
    let priceString = jQuery("#product-price-<?php echo($block->getProductId()); ?> .price").text();
    let endOfString = priceString.slice(-4);
    let basePrice=<?php echo $block->getProductAmount(); ?>;
    let price = priceString.replace(/[^0-9.,+]+/gi,'');

    if(price.charAt(price.length-3) == ','){
      price = price.substr(0, price.length-3)+'.'+price.substr(price.length-2);
    }
    price = price.replace(/,/g , '');

    if(basePrice >= threshold){
      document.getElementById("dividoWidget").setAttribute('data-amount', price * 100);
      document.getElementById("dividoWidget").style.display = "";
      __widgetInstance.init()

    }else{
      document.getElementById("dividoWidget").style.display = "none";
    }
  }

  if (jQuery(".product-options-wrapper")[0]){
    // Do something if class exists
    var wrapper = jQuery(".product-options-wrapper")[0];
    wrapper.addEventListener('click',updatePrice);
  }
  updatePrice();
});
</script>
<?php } ?>
