<?php /* @var $block \Divido\DividoFinancing\Block\Product\View\Extra */?>
<?php if($block->loadWidget()){ ?>
  <div id='dividoWidget' 
    data-calculator-widget 
    data-plans="<?php echo $block->getProductPlans(); ?>"
    data-amount="<?php echo $block->getAmount(); ?>" 
    data-mode="lightbox"
  ></div>
<script>
require(['jquery'], function($){
  var options = $(".product-options-wrapper input, .product-options-wrapper select");
  for(var iteration = 0; iteration < options.length; iteration++){
    var option = options[iteration];
    option.addEventListener('change', function(){
      setTimeout(updatePrice,50);
    })
    option.addEventListener('click',updatePrice);
  }
  var updatePrice = function(){
    let threshold = <?php echo $block->getThreshold(); ?>;
    let price = $("#product-price-<?php echo($block->getProductId()); ?> .price").text().replace(/[^0-9.+]+/gi,'');
    if(price >= threshold){
      document.getElementById("dividoWidget").setAttribute('data-amount', price * 100);
      document.getElementById("dividoWidget").style.display = "";
      __widgetInstance.init()

    }else{
      document.getElementById("dividoWidget").style.display = "none";
    }
  }
    // add update price event listener on click
    //var wrapper = $(".product-options-wrapper")[0];
    //wrapper.addEventListener('click',updatePrice);
    updatePrice();
});
</script>
<?php } ?>