<?php $application = $block->getApplication(); ?>

<?php if($application !== null){ ?>
<div id="pbdNotification">
    <div class="notification">
        Please note you can only be refunded &pound;<?= $application['refundable']['float'] ?> currently.
        You must contact your lender in order to obtain a refund for any deposit, etc.
    </div>
    <?php if (isset($application['reasons']) && is_iterable($application['reasons'])){ ?>
    <div id="pbdReason">
        <div>You must specify one of the following reasons for the refund to be successfully processed:</div>
        <div class='form'>
            <label for="refund_reasons">Refund Reason:</label>
            <select name='refund_reason' name='refund_reasons' id='refundReason'>
                <?php foreach ($application['reasons'] as $key => $value) { ?>
                    <option value='<?= $key ?>'><?= $value ?></option>
                <?php } ?>
            </select>
        </div>
    </div>
    <?php } ?>
</div>
<?php } ?>